config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :articles, :only => [:index, :show]

  root  'static_pages#index'

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords" }

  get 'cms_config' => 'application#cms_config'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of [:title,:content]
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  has_many :dish_products
  has_many :products, through: :dish_products
  accepts_nested_attributes_for :dish_products

  validates :name, :presence => true
  validates :name, :uniqueness => { :case_sensitive => false }
  validates :name, :uniqueness => true
end

app/models/dish_product.rb
class DishProduct < ActiveRecord::Base
  belongs_to :dish
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_category
  has_many :dish_products
  has_many :dishes, through: :dish_products

  validates :product, :presence => true
  validates :product, :uniqueness => { :case_sensitive => false }
  validates :product, :uniqueness => true
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ACTIVITIES = [ 'Activity low', 'Activity medium', 'Activity high' ]

  validates :height, :presence => true, :inclusion => { :in => 100..220, :message => "The height must be between 100 and 220" }
  validates :weight, :presence => true, :inclusion => { :in => 40..220, :message => "The weight must be between 40 and 220" }
  validates :age, :presence => true, :inclusion => { :in => 15..70, :message => "The age must be between 15 and 70" }

  #validates_inclusion_of :gender, in: %w( 'Male', 'Female' )

  #validates_inclusion_of :lifestyle, in: %w( 'Activity low', 'Activity medium', 'Activity high' )


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def cms_config
    params = {"timestamp" => Time.now.to_i.to_s, "mode"=>"tinymce"}
    params = Cloudinary::Utils.sign_request(params)
    render :json=>{:cloudinary_cms_url=>"https://cloudinary.com/console/media_library/cms?#{params.to_query}"}
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :height, :weight, :age, :gender, :lifestyle) }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    if current_user.present?
      @user = current_user
    else
      @user = User.new
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/index.html.erb
<div class="container" xmlns="http://www.w3.org/1999/html">

  <p id="notice"><%= notice %></p>

  <h2 class="green_title">Listing Articles</h2>

  <div class="row">
    <div class="col-sm-12" style="background-color:lavender;">
      <% @articles.each do |article| %>

          <ul class="article_list">
            <li>
              <div><%= (article.created_at.strftime('%Y-%b-%d')) if article.created_at.present? %></div>

              <div><%= article.title %></div>

              <div><%= truncate(article.content) if article.content.present? %></div>


            </li>
          </ul>

      <% end %>
      <br><br>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-12" align="center" style="background-color:lavender;">
         <%= link_to image_tag('eatcalc_footer.png', alt: "Rails"), root_path %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-sm-12" align="center" style="background-color:lavender;">

        <%= link_to image_tag('eatcalc_header.png', alt: "Rails"), root_path %>
      </div>
      <div class="pull-right">
        <div class="col-sm-12" align="center">
          <nav>
            <ul class="nav nav-pills" role="tablist">
              <li class="active"><%= link_to "Home", root_path %></li>
              <li><%= link_to "EatLog", '#' %></li>
              <li><%= link_to "Analysis", '#' %></li>
              <li><%= link_to "ReadyMealsCalc", '#' %></li>
              <li><%= link_to "Blogs&Info", articles_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EatCalc</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">


</head>
<body>

<%= render 'layouts/header' %>

<p class="notice"><%= notice %></p>

<p class="alert"><%= alert %></p>

<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/index.html.erb
<div class="container" xmlns="http://www.w3.org/1999/html">
  <h1 class="green_title">Be Healthy, wealthy and wise!</h1>

  <div class="row">
    <div class="col-sm-4">
      <br>

      <p>
        <%= link_to 'Sign In', '#', id: 'show_sing_in_form' %>
      </p>

      <div class="cup<% if user_signed_in? %> clear<% end %>" >

        <% if user_signed_in? %>
            <div class='Hi_email'>
            <p >Hi, </br><%= @user.email %>!</p>

            <%= link_to 'Log Out', destroy_user_session_path, :method => :delete %>
            </div>

        <% else %>
            <%= form_for(@user, url: session_path(@user), html: {id: 'signin-form'}) do |f| %>
            <div class="form-group1">
              <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder: 'email' %>
            </div>
            <div class="form-group">
              <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder: 'password'  %>
            </div>
              <%= f.submit "Log in" %>
            <% end %>
        <% end %>
      </div>
      <br>

      <p>
        <%= link_to 'Not Singed Up yet? Sign Up Now!', new_user_registration_path, :method => :get %>
      </p>
      <br>

    </div>
    <div class="col-sm-8">
      <p>
        Here we consider the calorie and nutritional value (protein, fat and carbohydrates) of food eaten within a
        certain period - day, week, month e.c.<br><br>
        In fact, we are in a diary and make corrections in the diet in order to achieve certain goals.<br><br>
        The aim of the project is the organization of a healthy diet and weight control.<br><br>
      </p>
    </div>
  </div>
</div>
<script>
  $('#show_sing_in_form').click(function (e) {
    e.preventDefault();
    $('.new_user').toggle();
  });
</script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>